### ISSUE TITLE
Refactor: Move Route Logic to Separate Controller Files

### ISSUE THREAD

**Issue by Zish303** [manascb1344/Online-Auction-System#13]
## Description:
Currently, all route functions are defined in a same file. To improve code readability and maintainability, each route file should have its own controller file to handle the logic.

## Tasks:
- Create a controllers directory.
- Move existing route logic to its controller files.
- Example:
1. /auction route -> controllers/auctionController.js
2. /transaction route -> controllers/transactionController.js

**Comment by iamtehmooramjad** [comment]
Hi, I want to work on this refactoring, Can you assign it to me?

**Comment by manascb1344** [comment]
> Hi, I want to work on this refactoring, Can you assign it to me?

Sure!!

**Comment by Zish303** [comment]
I wanted to work on it.

**Comment by Zish303** [comment]
@manascb1344 Can I work on this?

**Comment by manascb1344** [comment]
Yes!

**Comment by manascb1344** [comment]
I haven't received any updates, so I will be unassigning @iamtehmooramjad from the issue
